dist: bionic

language: go
go:
  - 1.13.x

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  - go test -v github.com/fogfish/gurl/...
  - $GOPATH/bin/overalls -project=github.com/fogfish/gurl 
  - $GOPATH/bin/goveralls -service=travis-ci
