dist: bionic

language: go
go:
  - 1.13.x
  - 1.12.x
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -cover -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -service=travis-ci
